title: BoxingBytes
remote_theme: pages-themes/cayman@v0.2.0
description: |
  I'm a student working on reinforcement learning and 
  multi-agent systems. My research explores the emergence of cooperation and intelligence in simulated societies. Ultimately, my goal is to understand how collective intelligence arises from individuals, and how these insights can guide real-world systems.
url: "https://BoxingBytes.github.io"
baseurl: ""
author: "Aguirre Max"
google_analytics: G-1X549WT3V1
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  projects:
    output: true
    permalink: /projects/:path/
  publications:
    output: true
    permalink: /publications/:path/
  highlights:
    output: true
    permalink: /highlights/:path/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: ""
      type: "highlights"
    values:
      layout: "highlight"
      
repository: BoxingBytes/BoxingBytes.github.io
github:
  repository_url: https://github.com/BoxingBytes/BoxingBytes.github.io
  repository_name: BoxingBytes.github.io
  owner_name: BoxingBytes